DT-2947: add ROLE_MANAGE_NOMIS_USER_ACCOUNT to /users/{username}
ministryofjustice/nomis-user-roles-api pull request #68
Opened 2021-12-03 11:40 UTC by neilmendum

In #45 @Mjwillis added `ROLE_MAINTAIN_ACCESS_ROLES`. I noticed that this endpoint didn't have `ROLE_MANAGE_NOMIS_USER_ACCOUNT` which we have on `findUsersByEmailAddress` and `findUsersByEmailAddressAndUsernames`

2021-12-03 14:16 UTC, andymarke requested changes
I think you have accidentally removed the `ROLE_MAINTAIN_ACCESS_ROLES_ADMIN` ?

2021-12-03 14:16 UTC, andymarke commented on src/main/kotlin/uk/gov/justice/digital/hmpps/nomisuserrolesapi/resource/UserResource.kt
>    @GetMapping("/{username}")
I think it requires all 3:

- ROLE_MAINTAIN_ACCESS_ROLES_ADMIN
- ROLE_MAINTAIN_ACCESS_ROLES
- ROLE_MANAGE_NOMIS_USER_ACCOUNT

2021-12-03 14:16 UTC, andymarke commented on src/test/kotlin/uk/gov/justice/digital/hmpps/nomisuserrolesapi/resource/UserAccountResourceIntTest.kt
> +        .headers(setAuthorisation(roles = listOf("ROLE_MAINTAIN_ACCESS_ROLES")))
Then I suppose add an additional test for ROLE_MANAGE_NOMIS_USER_ACCOUNT rather than replacing ROLE_MAINTAIN_ACCESS_ROLES_ADMIN

2021-12-06 08:40 UTC, closed without merging

2021-12-06 08:41 UTC, neilmendum commented
Closing as per [this discussion](https://mojdt.slack.com/archives/C012FNNQ4A3/p1638541709029200?thread_ts=1638540484.027300&cid=C012FNNQ4A3)